export const actionTypes = {
  USER_REGISTER: 'USER_REGISTER',
  USER_LOGIN: 'USER_LOGIN',
  USER_DATA: 'USER_DATA',
  ADD_FETCH_SUCCESS: 'ADD FETCH_SUCCESS',
  // Products
  DELETE_PRODUCT_FROM_PRODUCTLIST: 'DELETE_PRODUCT_FROM_PRODUCTLIST',
  ADD_PRODUCT_BY_DATE: 'ADD_PRODUCT_BY_DATE',
  GET_ALL_PRODUCTS: 'GET ALL PRODUCTS',
  GET_PRODUCTS_PER_DAY: 'GET PRODUCTS PER DAY',
  SHOW_MODAL_PRODUCTS: 'SHOW MODAL PRODUCTS',
  CLOSE_MODAL_PRODUCTS: 'CLOSE MODAL PRODUCTS',
  TOOGLE_FETCH_PROD_BY_DAY_LOADER: 'TOOGLE FETCH LOADER',
  FETCH_ERROR: 'FETCH ERROR',
  ADD_PRODUCT_BY_DAY: 'ADD PRODUCT BY DAY',
  ADD_ALL_DATA: 'ADD: ALL_DATA',
  // Date
  SET_DATE: 'SET DATE',
  // Session
  CLEAR_SESSION: 'CLEAR_SESSION'
};

export const test = {};
